env:
  AWS_DEFAULT_REGION: 'ap-southeast-2'

branches:
  only: 
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip jq
  - sudo pip install awscli

install:
  # Download and install the latest version of terraform
  - curl -o terraform.zip $(echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip")
  - unzip terraform.zip && sudo mv terraform /usr/local/bin/terraform
  - terraform -v

env:
 - WORKSPACE=datacube-prod

script:
  - cd infrastructure
  - terraform init -backend-config workspaces/$WORKSPACE/backend.cfg
  - terraform workspace new $WORKSPACE || terraform workspace select $WORKSPACE
  - terraform plan -input=false -var-file="workspaces/$WORKSPACE/terraform.tfvars"
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then terraform apply -auto-approve -var-file="workspaces/$WORKSPACE/terraform.tfvars" -input=false; fi'
